Traceback (most recent call last):
  File "/Users/tsauter/venv/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/tsauter/venv/lib/python3.7/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## The NOAA ESRL server is shutdown! January 2019
ncep_url = "https://psl.noaa.gov/thredds/catalog/Datasets/ncep.reanalysis.derived/pressure/catalog.html?dataset=Datasets/ncep.reanalysis.derived/"
ncep_air = xr.open_dataset("https://psl.noaa.gov/thredds/fileServer/Datasets/ncep.reanalysis.derived/pressure/air.mon.ltm.1981-2010.nc",use_cftime=True)

ncep_air
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m~/venv/lib/python3.7/site-packages/xarray/backends/file_manager.py[0m in [0;36m_acquire_with_cache_info[0;34m(self, needs_lock)[0m
[1;32m    198[0m             [0;32mtry[0m[0;34m:[0m[0;34m[0m[0m
[0;32m--> 199[0;31m                 [0mfile[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_cache[0m[0;34m[[0m[0mself[0m[0;34m.[0m[0m_key[0m[0;34m][0m[0;34m[0m[0m
[0m[1;32m    200[0m             [0;32mexcept[0m [0mKeyError[0m[0;34m:[0m[0;34m[0m[0m

[0;32m~/venv/lib/python3.7/site-packages/xarray/backends/lru_cache.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m     52[0m         [0;32mwith[0m [0mself[0m[0;34m.[0m[0m_lock[0m[0;34m:[0m[0;34m[0m[0m
[0;32m---> 53[0;31m             [0mvalue[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_cache[0m[0;34m[[0m[0mkey[0m[0;34m][0m[0;34m[0m[0m
[0m[1;32m     54[0m             [0mself[0m[0;34m.[0m[0m_cache[0m[0;34m.[0m[0mmove_to_end[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0m

[0;31mKeyError[0m: [<class 'netCDF4._netCDF4.Dataset'>, ('https://psl.noaa.gov/thredds/fileServer/Datasets/ncep.reanalysis.derived/pressure/air.mon.ltm.1981-2010.nc',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m/var/folders/tt/q4k5594x1tz82j1yrmtkdw080000gn/T/ipykernel_2893/3502068674.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m## The NOAA ESRL server is shutdown! January 2019[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mncep_url[0m [0;34m=[0m [0;34m"https://psl.noaa.gov/thredds/catalog/Datasets/ncep.reanalysis.derived/pressure/catalog.html?dataset=Datasets/ncep.reanalysis.derived/"[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mncep_air[0m [0;34m=[0m [0mxr[0m[0;34m.[0m[0mopen_dataset[0m[0;34m([0m[0;34m"https://psl.noaa.gov/thredds/fileServer/Datasets/ncep.reanalysis.derived/pressure/air.mon.ltm.1981-2010.nc"[0m[0;34m,[0m[0muse_cftime[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mncep_air[0m[0;34m[0m[0m

[0;32m~/venv/lib/python3.7/site-packages/xarray/backends/api.py[0m in [0;36mopen_dataset[0;34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, *args, **kwargs)[0m
[1;32m    499[0m         [0mdrop_variables[0m[0;34m=[0m[0mdrop_variables[0m[0;34m,[0m[0;34m[0m[0m
[1;32m    500[0m         [0;34m**[0m[0mdecoders[0m[0;34m,[0m[0;34m[0m[0m
[0;32m--> 501[0;31m         [0;34m**[0m[0mkwargs[0m[0;34m,[0m[0;34m[0m[0m
[0m[1;32m    502[0m     )
[1;32m    503[0m     ds = _dataset_from_backend_dataset(

[0;32m~/venv/lib/python3.7/site-packages/xarray/backends/netCDF4_.py[0m in [0;36mopen_dataset[0;34m(self, filename_or_obj, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, use_cftime, decode_timedelta, group, mode, format, clobber, diskless, persist, lock, autoclose)[0m
[1;32m    558[0m             [0mpersist[0m[0;34m=[0m[0mpersist[0m[0;34m,[0m[0;34m[0m[0m
[1;32m    559[0m             [0mlock[0m[0;34m=[0m[0mlock[0m[0;34m,[0m[0;34m[0m[0m
[0;32m--> 560[0;31m             [0mautoclose[0m[0;34m=[0m[0mautoclose[0m[0;34m,[0m[0;34m[0m[0m
[0m[1;32m    561[0m         )
[1;32m    562[0m [0;34m[0m[0m

[0;32m~/venv/lib/python3.7/site-packages/xarray/backends/netCDF4_.py[0m in [0;36mopen[0;34m(cls, filename, mode, format, group, clobber, diskless, persist, lock, lock_maker, autoclose)[0m
[1;32m    378[0m             [0mnetCDF4[0m[0;34m.[0m[0mDataset[0m[0;34m,[0m [0mfilename[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0mmode[0m[0;34m,[0m [0mkwargs[0m[0;34m=[0m[0mkwargs[0m[0;34m[0m[0m
[1;32m    379[0m         )
[0;32m--> 380[0;31m         [0;32mreturn[0m [0mcls[0m[0;34m([0m[0mmanager[0m[0;34m,[0m [0mgroup[0m[0;34m=[0m[0mgroup[0m[0;34m,[0m [0mmode[0m[0;34m=[0m[0mmode[0m[0;34m,[0m [0mlock[0m[0;34m=[0m[0mlock[0m[0;34m,[0m [0mautoclose[0m[0;34m=[0m[0mautoclose[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m    381[0m [0;34m[0m[0m
[1;32m    382[0m     [0;32mdef[0m [0m_acquire[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mneeds_lock[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0m

[0;32m~/venv/lib/python3.7/site-packages/xarray/backends/netCDF4_.py[0m in [0;36m__init__[0;34m(self, manager, group, mode, lock, autoclose)[0m
[1;32m    326[0m         [0mself[0m[0;34m.[0m[0m_group[0m [0;34m=[0m [0mgroup[0m[0;34m[0m[0m
[1;32m    327[0m         [0mself[0m[0;34m.[0m[0m_mode[0m [0;34m=[0m [0mmode[0m[0;34m[0m[0m
[0;32m--> 328[0;31m         [0mself[0m[0;34m.[0m[0mformat[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mds[0m[0;34m.[0m[0mdata_model[0m[0;34m[0m[0m
[0m[1;32m    329[0m         [0mself[0m[0;34m.[0m[0m_filename[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mds[0m[0;34m.[0m[0mfilepath[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0m
[1;32m    330[0m         [0mself[0m[0;34m.[0m[0mis_remote[0m [0;34m=[0m [0mis_remote_uri[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_filename[0m[0;34m)[0m[0;34m[0m[0m

[0;32m~/venv/lib/python3.7/site-packages/xarray/backends/netCDF4_.py[0m in [0;36mds[0;34m(self)[0m
[1;32m    387[0m     [0;34m@[0m[0mproperty[0m[0;34m[0m[0m
[1;32m    388[0m     [0;32mdef[0m [0mds[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0m
[0;32m--> 389[0;31m         [0;32mreturn[0m [0mself[0m[0;34m.[0m[0m_acquire[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m    390[0m [0;34m[0m[0m
[1;32m    391[0m     [0;32mdef[0m [0mopen_store_variable[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mname[0m[0;34m,[0m [0mvar[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0m

[0;32m~/venv/lib/python3.7/site-packages/xarray/backends/netCDF4_.py[0m in [0;36m_acquire[0;34m(self, needs_lock)[0m
[1;32m    381[0m [0;34m[0m[0m
[1;32m    382[0m     [0;32mdef[0m [0m_acquire[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mneeds_lock[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0m
[0;32m--> 383[0;31m         [0;32mwith[0m [0mself[0m[0;34m.[0m[0m_manager[0m[0;34m.[0m[0macquire_context[0m[0;34m([0m[0mneeds_lock[0m[0;34m)[0m [0;32mas[0m [0mroot[0m[0;34m:[0m[0;34m[0m[0m
[0m[1;32m    384[0m             [0mds[0m [0;34m=[0m [0m_nc4_require_group[0m[0;34m([0m[0mroot[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0m_group[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0m_mode[0m[0;34m)[0m[0;34m[0m[0m
[1;32m    385[0m         [0;32mreturn[0m [0mds[0m[0;34m[0m[0m

[0;32m/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py[0m in [0;36m__enter__[0;34m(self)[0m
[1;32m    110[0m         [0;32mdel[0m [0mself[0m[0;34m.[0m[0margs[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mkwds[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mfunc[0m[0;34m[0m[0m
[1;32m    111[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0m
[0;32m--> 112[0;31m             [0;32mreturn[0m [0mnext[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mgen[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m    113[0m         [0;32mexcept[0m [0mStopIteration[0m[0;34m:[0m[0;34m[0m[0m
[1;32m    114[0m             [0;32mraise[0m [0mRuntimeError[0m[0;34m([0m[0;34m"generator didn't yield"[0m[0;34m)[0m [0;32mfrom[0m [0;32mNone[0m[0;34m[0m[0m

[0;32m~/venv/lib/python3.7/site-packages/xarray/backends/file_manager.py[0m in [0;36macquire_context[0;34m(self, needs_lock)[0m
[1;32m    185[0m     [0;32mdef[0m [0macquire_context[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mneeds_lock[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0m
[1;32m    186[0m         [0;34m"""Context manager for acquiring a file."""[0m[0;34m[0m[0m
[0;32m--> 187[0;31m         [0mfile[0m[0;34m,[0m [0mcached[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_acquire_with_cache_info[0m[0;34m([0m[0mneeds_lock[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m    188[0m         [0;32mtry[0m[0;34m:[0m[0;34m[0m[0m
[1;32m    189[0m             [0;32myield[0m [0mfile[0m[0;34m[0m[0m

[0;32m~/venv/lib/python3.7/site-packages/xarray/backends/file_manager.py[0m in [0;36m_acquire_with_cache_info[0;34m(self, needs_lock)[0m
[1;32m    203[0m                     [0mkwargs[0m [0;34m=[0m [0mkwargs[0m[0;34m.[0m[0mcopy[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0m
[1;32m    204[0m                     [0mkwargs[0m[0;34m[[0m[0;34m"mode"[0m[0;34m][0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_mode[0m[0;34m[0m[0m
[0;32m--> 205[0;31m                 [0mfile[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0m_opener[0m[0;34m([0m[0;34m*[0m[0mself[0m[0;34m.[0m[0m_args[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m    206[0m                 [0;32mif[0m [0mself[0m[0;34m.[0m[0m_mode[0m [0;34m==[0m [0;34m"w"[0m[0;34m:[0m[0;34m[0m[0m
[1;32m    207[0m                     [0;31m# ensure file doesn't get overriden when opened again[0m[0;34m[0m[0;34m[0m[0m

[0;32msrc/netCDF4/_netCDF4.pyx[0m in [0;36mnetCDF4._netCDF4.Dataset.__init__[0;34m()[0m

[0;32msrc/netCDF4/_netCDF4.pyx[0m in [0;36mnetCDF4._netCDF4._ensure_nc_success[0;34m()[0m

[0;31mOSError[0m: [Errno -68] NetCDF: I/O failure: b'https://psl.noaa.gov/thredds/fileServer/Datasets/ncep.reanalysis.derived/pressure/air.mon.ltm.1981-2010.nc'
OSError: [Errno -68] NetCDF: I/O failure: b'https://psl.noaa.gov/thredds/fileServer/Datasets/ncep.reanalysis.derived/pressure/air.mon.ltm.1981-2010.nc'

